#![warn(unused_mut)]

[package]
name = "mc-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
json = "0.12.4"
tokio = { version = "1.48.0", features = [ "full" ], default-features = false }
